# Generated by Django 4.1.4 on 2023-04-16 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("file", "0001_initial"),
        ("post", "0001_initial"),
        ("userprofile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="filesubcategory",
            name="subCategoryId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="post.subcategory"
            ),
        ),
        migrations.AddField(
            model_name="fileprofile",
            name="fileId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="file.file"
            ),
        ),
        migrations.AddField(
            model_name="fileprofile",
            name="profileId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.usersprofile",
            ),
        ),
        migrations.AddField(
            model_name="filepost",
            name="fileId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="file.file"
            ),
        ),
        migrations.AddField(
            model_name="filepost",
            name="postId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="post.post"
            ),
        ),
        migrations.AddField(
            model_name="filecategory",
            name="categoryId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="post.category"
            ),
        ),
        migrations.AddField(
            model_name="filecategory",
            name="fileId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="file.file"
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="userId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
