# Generated by Django 4.1.7 on 2023-06-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="deletedAt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="deletedAt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="deletedAt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="deletedAt",
            field=models.DateTimeField(null=True),
        ),
    ]
