# Generated by Django 4.1.7 on 2023-06-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordreset",
            name="deletedAt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="deletedAt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="verifiedemail",
            name="deletedAt",
            field=models.DateTimeField(null=True),
        ),
    ]
