# Generated by Django 4.1.4 on 2023-02-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("userprofile", "0001_initial"),
        ("post", "0001_initial"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="posts",
            field=models.ManyToManyField(related_name="users_posts", to="post.post"),
        ),
        migrations.AddField(
            model_name="users",
            name="profile",
            field=models.ManyToManyField(to="userprofile.usersprofile"),
        ),
        migrations.AddField(
            model_name="users",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
