# Generated by Django 4.1.4 on 2023-03-02 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meta.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsersProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=64, null=True)),
                ("lastName", models.CharField(max_length=64, null=True)),
                ("image", models.FileField(upload_to="static/uploads/")),
                ("dateOfBirth", models.DateTimeField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("details", models.TextField(max_length=500, null=True)),
                ("zipcode", models.CharField(max_length=15, null=True)),
                ("address", models.CharField(max_length=150, null=True)),
                ("city", models.CharField(max_length=150, null=True)),
                (
                    "region",
                    models.CharField(max_length=150, null=True, verbose_name="state"),
                ),
                ("country", models.CharField(max_length=150, null=True)),
                ("longitude", models.CharField(max_length=15, null=True)),
                ("latitude", models.CharField(max_length=15, null=True)),
                (
                    "popularity",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
