# Generated by Django 4.1.7 on 2023-06-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersprofile",
            name="deletedAt",
            field=models.DateTimeField(null=True),
        ),
    ]
