# Generated by Django 4.1.4 on 2023-04-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file", "0002_initial"),
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersprofile",
            name="image",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="usersprofile",
            name="media",
            field=models.ManyToManyField(through="file.FileProfile", to="file.file"),
        ),
    ]
